name: demoproject
description: "This is the assessment project"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  firebase_core_platform_interface: ^5.0.0
  firebase_auth: ^4.17.8
  fluentui_system_icons: ^1.1.234
  fluentui_icons:
  dropdown_button2: ^2.3.9
  fl_chart:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/filter.png"


flutter:
  assets:
    - assets/
    - assets/images/

  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf


