name: demoproject
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  firebase_core_platform_interface: ^5.0.0
  firebase_auth: ^4.17.8
  getwidget: ^4.0.0
  flutter_otp_text_field: ^1.1.0+2
  cloud_firestore: ^4.15.8
  multi_select_flutter: ^4.0.0
  provider: ^6.1.2
  csc_picker: ^0.2.7
  date_picker_plus: ^3.0.2
  multiselect: ^0.1.0
  animate_do: ^3.1.2
  fluentui_system_icons: ^1.1.234
  smooth_page_indicator: ^1.1.0
  google_sign_in: ^6.2.1
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  animate_do: ^3.1.2



flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/logo/

  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-VariableFont_wdth,wght.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico.ttf

