// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgqpWmnzC3n3jOTSH0IAcf0cECH2WT2Ac',
    appId: '1:1064140295584:web:c3354a78f72f9d764ae8c5',
    messagingSenderId: '1064140295584',
    projectId: 'fir-project-54ed4',
    authDomain: 'fir-project-54ed4.firebaseapp.com',
    storageBucket: 'fir-project-54ed4.appspot.com',
    measurementId: 'G-CHSZ58X89R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7qxW2aPqHFg_lP87VhBtWn4S3PyU29nk',
    appId: '1:1064140295584:android:22705af96ce2b3e74ae8c5',
    messagingSenderId: '1064140295584',
    projectId: 'fir-project-54ed4',
    storageBucket: 'fir-project-54ed4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaHtsaYRwmgC-2FmnYpKrozzvSPxABQMo',
    appId: '1:1064140295584:ios:03edaadd04e78e8b4ae8c5',
    messagingSenderId: '1064140295584',
    projectId: 'fir-project-54ed4',
    storageBucket: 'fir-project-54ed4.appspot.com',
    iosBundleId: 'com.example.demoproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaHtsaYRwmgC-2FmnYpKrozzvSPxABQMo',
    appId: '1:1064140295584:ios:fe8201dea5e11be84ae8c5',
    messagingSenderId: '1064140295584',
    projectId: 'fir-project-54ed4',
    storageBucket: 'fir-project-54ed4.appspot.com',
    iosBundleId: 'com.example.demoproject.RunnerTests',
  );
}
